-- MySQL Script generated by MySQL Workbench
-- Wed Dec 16 18:43:02 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tzeentch-shop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tzeentch-shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tzeentch-shop` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `tzeentch-shop` ;

-- -----------------------------------------------------
-- Table `tzeentch-shop`.`picture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tzeentch-shop`.`picture` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `url` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tzeentch-shop`.`author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tzeentch-shop`.`author` (
  `id` INT(11) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `picture_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK3mys7ia4ff17p0m4u1at4qetp` (`picture_id` ASC) VISIBLE,
  CONSTRAINT `FK3mys7ia4ff17p0m4u1at4qetp`
    FOREIGN KEY (`picture_id`)
    REFERENCES `tzeentch-shop`.`picture` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tzeentch-shop`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tzeentch-shop`.`user` (
  `id` INT(11) NOT NULL,
  `activation_code` VARCHAR(255) NULL DEFAULT NULL,
  `active` BIT(1) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `google_id` VARCHAR(255) NULL DEFAULT NULL,
  `last_visit` DATETIME(6) NULL DEFAULT NULL,
  `locale` VARCHAR(255) NULL DEFAULT NULL,
  `username` VARCHAR(255) NOT NULL,
  `picture_id` INT(11) NULL DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL,
  `expired` BIT(1) NULL DEFAULT NULL,
  `locked` BIT(1) NULL DEFAULT NULL,
  `dtype` VARCHAR(31) NOT NULL,
  `credit_card_number` VARCHAR(255) NULL DEFAULT NULL,
  `sum_of_money` DECIMAL(19,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_ob8kqyqqgmefl0aco34akdtpe` (`email` ASC) VISIBLE,
  UNIQUE INDEX `UK_sb8bbouer5wak8vyiiy4pf2bx` (`username` ASC) VISIBLE,
  UNIQUE INDEX `UK_gj2fy3dcix7ph7k8684gka40c` (`name` ASC) VISIBLE,
  UNIQUE INDEX `UK_lfismxng57avbbo40y5tbppf7` (`google_id` ASC) VISIBLE,
  INDEX `FKgrhwkuv1742mbmvbqng5nvis2` (`picture_id` ASC) VISIBLE,
  CONSTRAINT `FKgrhwkuv1742mbmvbqng5nvis2`
    FOREIGN KEY (`picture_id`)
    REFERENCES `tzeentch-shop`.`picture` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tzeentch-shop`.`rating_param`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tzeentch-shop`.`rating_param` (
  `id` INT(11) NOT NULL,
  `rating` DOUBLE NULL DEFAULT NULL,
  `rated_book_id` INT(11) NULL DEFAULT NULL,
  `voted_user_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK92c2bf7cefnsa16hytisvwfmr` (`rated_book_id` ASC) VISIBLE,
  INDEX `FKmdrbwisyxi1swqxe6c5nttm5k` (`voted_user_id` ASC) VISIBLE,
  CONSTRAINT `FK92c2bf7cefnsa16hytisvwfmr`
    FOREIGN KEY (`rated_book_id`)
    REFERENCES `tzeentch-shop`.`book` (`id`),
  CONSTRAINT `FKmdrbwisyxi1swqxe6c5nttm5k`
    FOREIGN KEY (`voted_user_id`)
    REFERENCES `tzeentch-shop`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tzeentch-shop`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tzeentch-shop`.`book` (
  `id` INT(11) NOT NULL,
  `availability` INT(11) NULL DEFAULT NULL,
  `book_status` VARCHAR(255) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `popularity` INT(11) NULL DEFAULT NULL,
  `price` DECIMAL(19,2) NULL DEFAULT NULL,
  `translation_status` VARCHAR(255) NULL DEFAULT NULL,
  `picture_id` INT(11) NULL DEFAULT NULL,
  `print_time` DATETIME(6) NULL DEFAULT NULL,
  `rating` DOUBLE NULL DEFAULT NULL,
  `url` VARCHAR(255) NULL DEFAULT NULL,
  `file_name` VARCHAR(255) NULL DEFAULT NULL,
  `rating_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKi9ghuw3k1cb6rluk4rgen2exl` (`picture_id` ASC) VISIBLE,
  INDEX `FKplhldhkbk2gc9lw1u4qv3fdow` (`rating_id` ASC) VISIBLE,
  CONSTRAINT `FKi9ghuw3k1cb6rluk4rgen2exl`
    FOREIGN KEY (`picture_id`)
    REFERENCES `tzeentch-shop`.`picture` (`id`),
  CONSTRAINT `FKplhldhkbk2gc9lw1u4qv3fdow`
    FOREIGN KEY (`rating_id`)
    REFERENCES `tzeentch-shop`.`rating_param` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tzeentch-shop`.`book_authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tzeentch-shop`.`book_authors` (
  `authors_id` INT(11) NOT NULL,
  `book_id` INT(11) NOT NULL,
  PRIMARY KEY (`authors_id`, `book_id`),
  INDEX `FKs4xm7q8i3uxvaiswj1c35nnxw` (`book_id` ASC) VISIBLE,
  CONSTRAINT `FK551i3sllw1wj7ex6nir16blsm`
    FOREIGN KEY (`authors_id`)
    REFERENCES `tzeentch-shop`.`author` (`id`),
  CONSTRAINT `FKs4xm7q8i3uxvaiswj1c35nnxw`
    FOREIGN KEY (`book_id`)
    REFERENCES `tzeentch-shop`.`book` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tzeentch-shop`.`book_genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tzeentch-shop`.`book_genre` (
  `id` INT(11) NOT NULL,
  `genres` VARCHAR(255) NULL DEFAULT NULL,
  INDEX `FKdju06untveesmbb7rqdfho1cf` (`id` ASC) VISIBLE,
  CONSTRAINT `FKdju06untveesmbb7rqdfho1cf`
    FOREIGN KEY (`id`)
    REFERENCES `tzeentch-shop`.`book` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tzeentch-shop`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tzeentch-shop`.`review` (
  `id` INT(11) NOT NULL,
  `comment` VARCHAR(255) NULL DEFAULT NULL,
  `data` DATETIME(6) NULL DEFAULT NULL,
  `mark` INT(11) NULL DEFAULT NULL,
  `author_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKhaxvalsvi9mqlu2kq5ev0wgys` (`author_id` ASC) VISIBLE,
  CONSTRAINT `FKhaxvalsvi9mqlu2kq5ev0wgys`
    FOREIGN KEY (`author_id`)
    REFERENCES `tzeentch-shop`.`user` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tzeentch-shop`.`book_rewiew`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tzeentch-shop`.`book_rewiew` (
  `review_id` INT(11) NOT NULL,
  `book_id` INT(11) NOT NULL,
  PRIMARY KEY (`review_id`, `book_id`),
  INDEX `FKdlre8ly6oukfdnik7abdgll85` (`book_id` ASC) VISIBLE,
  CONSTRAINT `FK75ds8s54ncjgn1f5r9c0u0rcw`
    FOREIGN KEY (`review_id`)
    REFERENCES `tzeentch-shop`.`review` (`id`),
  CONSTRAINT `FKdlre8ly6oukfdnik7abdgll85`
    FOREIGN KEY (`book_id`)
    REFERENCES `tzeentch-shop`.`book` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tzeentch-shop`.`translater`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tzeentch-shop`.`translater` (
  `id` INT(11) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `fio` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tzeentch-shop`.`book_translater`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tzeentch-shop`.`book_translater` (
  `translater_id` INT(11) NOT NULL,
  `book_id` INT(11) NOT NULL,
  PRIMARY KEY (`translater_id`, `book_id`),
  INDEX `FKh2fakw6pdxvv5u9w46k5g1n8n` (`book_id` ASC) VISIBLE,
  CONSTRAINT `FKh2fakw6pdxvv5u9w46k5g1n8n`
    FOREIGN KEY (`book_id`)
    REFERENCES `tzeentch-shop`.`book` (`id`),
  CONSTRAINT `FKm3g2vtyinarq7abjhf1xkfjbd`
    FOREIGN KEY (`translater_id`)
    REFERENCES `tzeentch-shop`.`translater` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tzeentch-shop`.`book_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tzeentch-shop`.`book_users` (
  `user_id` INT(11) NOT NULL,
  `book_id` INT(11) NOT NULL,
  PRIMARY KEY (`user_id`, `book_id`),
  INDEX `FK1hk6yvyq2iag216km96wepdel` (`book_id` ASC) VISIBLE,
  CONSTRAINT `FK1hk6yvyq2iag216km96wepdel`
    FOREIGN KEY (`book_id`)
    REFERENCES `tzeentch-shop`.`book` (`id`),
  CONSTRAINT `FKrl1hotgyjy75v4uem68tje7hp`
    FOREIGN KEY (`user_id`)
    REFERENCES `tzeentch-shop`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tzeentch-shop`.`chapter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tzeentch-shop`.`chapter` (
  `id` INT(11) NOT NULL,
  `chapter_text` VARCHAR(255) NULL DEFAULT NULL,
  `number_of_chapter` INT(11) NULL DEFAULT NULL,
  `next_chapter_id` INT(11) NULL DEFAULT NULL,
  `prev_chapter_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKlkmjxiqvgxxd0fffypar006kq` (`next_chapter_id` ASC) VISIBLE,
  INDEX `FKc9glyv9pj8wh5v4yxbwr22f8` (`prev_chapter_id` ASC) VISIBLE,
  CONSTRAINT `FKc9glyv9pj8wh5v4yxbwr22f8`
    FOREIGN KEY (`prev_chapter_id`)
    REFERENCES `tzeentch-shop`.`chapter` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `FKlkmjxiqvgxxd0fffypar006kq`
    FOREIGN KEY (`next_chapter_id`)
    REFERENCES `tzeentch-shop`.`chapter` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tzeentch-shop`.`chapter_translater`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tzeentch-shop`.`chapter_translater` (
  `translater_id` INT(11) NOT NULL,
  `chapter_id` INT(11) NOT NULL,
  PRIMARY KEY (`translater_id`, `chapter_id`),
  INDEX `FK41xjmipo30j5xmgkacfba9vug` (`chapter_id` ASC) VISIBLE,
  CONSTRAINT `FK41xjmipo30j5xmgkacfba9vug`
    FOREIGN KEY (`chapter_id`)
    REFERENCES `tzeentch-shop`.`chapter` (`id`),
  CONSTRAINT `FKfbq1c5ro95fpye7ag4oi82msy`
    FOREIGN KEY (`translater_id`)
    REFERENCES `tzeentch-shop`.`translater` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tzeentch-shop`.`hibernate_sequence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tzeentch-shop`.`hibernate_sequence` (
  `next_val` BIGINT(20) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tzeentch-shop`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tzeentch-shop`.`room` (
  `id` INT(11) NOT NULL,
  `message` VARCHAR(255) NULL DEFAULT NULL,
  `print_time` DATETIME(6) NULL DEFAULT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `author_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_bwtkrldtq09e4rghbofc1a3q` (`title` ASC) VISIBLE,
  INDEX `FKivtwdosuv4bq7r5q51hvq5xd1` (`author_id` ASC) VISIBLE,
  CONSTRAINT `FKivtwdosuv4bq7r5q51hvq5xd1`
    FOREIGN KEY (`author_id`)
    REFERENCES `tzeentch-shop`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tzeentch-shop`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tzeentch-shop`.`message` (
  `id` INT(11) NOT NULL,
  `date` DATETIME(6) NOT NULL,
  `message` VARCHAR(255) NULL DEFAULT NULL,
  `room` VARCHAR(255) NULL DEFAULT NULL,
  `user_name` VARCHAR(255) NOT NULL,
  `room_id` INT(11) NULL DEFAULT NULL,
  `title` INT(11) NOT NULL,
  `author_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKl1kg5a2471cv6pkew0gdgjrmo` (`room_id` ASC) VISIBLE,
  INDEX `FKfsv5sprbvit5f7c23v6wjxe35` (`author_id` ASC) VISIBLE,
  CONSTRAINT `FKfsv5sprbvit5f7c23v6wjxe35`
    FOREIGN KEY (`author_id`)
    REFERENCES `tzeentch-shop`.`user` (`id`),
  CONSTRAINT `FKl1kg5a2471cv6pkew0gdgjrmo`
    FOREIGN KEY (`room_id`)
    REFERENCES `tzeentch-shop`.`room` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tzeentch-shop`.`news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tzeentch-shop`.`news` (
  `id` INT(11) NOT NULL,
  `message` VARCHAR(255) NULL DEFAULT NULL,
  `print_time` DATETIME(6) NULL DEFAULT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `author_id` INT(11) NULL DEFAULT NULL,
  `picture_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKrxsvhjf5khl0mf6jf3au0vqaf` (`author_id` ASC) VISIBLE,
  INDEX `FKs1w5cmt2cvb4jmo7xh62f0y4j` (`picture_id` ASC) VISIBLE,
  CONSTRAINT `FKrxsvhjf5khl0mf6jf3au0vqaf`
    FOREIGN KEY (`author_id`)
    REFERENCES `tzeentch-shop`.`user` (`id`),
  CONSTRAINT `FKs1w5cmt2cvb4jmo7xh62f0y4j`
    FOREIGN KEY (`picture_id`)
    REFERENCES `tzeentch-shop`.`picture` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tzeentch-shop`.`news_review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tzeentch-shop`.`news_review` (
  `review_id` INT(11) NOT NULL,
  `news_id` INT(11) NOT NULL,
  PRIMARY KEY (`review_id`, `news_id`),
  INDEX `FKo3qc2npa123a4j7p71yla92ta` (`news_id` ASC) VISIBLE,
  CONSTRAINT `FKo3qc2npa123a4j7p71yla92ta`
    FOREIGN KEY (`news_id`)
    REFERENCES `tzeentch-shop`.`news` (`id`),
  CONSTRAINT `FKsesbhckquekadv29y3tvnm566`
    FOREIGN KEY (`review_id`)
    REFERENCES `tzeentch-shop`.`review` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tzeentch-shop`.`rating_param_voted_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tzeentch-shop`.`rating_param_voted_user` (
  `rating_param_id` INT(11) NOT NULL,
  `voted_user_id` INT(11) NOT NULL,
  PRIMARY KEY (`rating_param_id`, `voted_user_id`),
  INDEX `FKpsjvcr4nljk6dgsdvw4bq4sgh` (`voted_user_id` ASC) VISIBLE,
  CONSTRAINT `FKpsjvcr4nljk6dgsdvw4bq4sgh`
    FOREIGN KEY (`voted_user_id`)
    REFERENCES `tzeentch-shop`.`user` (`id`),
  CONSTRAINT `FKqip45ub149budlw8k74f9osb2`
    FOREIGN KEY (`rating_param_id`)
    REFERENCES `tzeentch-shop`.`rating_param` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tzeentch-shop`.`related_book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tzeentch-shop`.`related_book` (
  `book_id` INT(11) NOT NULL,
  `related_books_id` INT(11) NOT NULL,
  PRIMARY KEY (`book_id`, `related_books_id`),
  INDEX `FK1iohg35v2xl84gd0ihm1d9ba3` (`related_books_id` ASC) VISIBLE,
  CONSTRAINT `FK1iohg35v2xl84gd0ihm1d9ba3`
    FOREIGN KEY (`related_books_id`)
    REFERENCES `tzeentch-shop`.`book` (`id`),
  CONSTRAINT `FK22ijxrtqaips4k1seseaa7irq`
    FOREIGN KEY (`book_id`)
    REFERENCES `tzeentch-shop`.`book` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tzeentch-shop`.`review_answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tzeentch-shop`.`review_answers` (
  `review_id` INT(11) NOT NULL,
  `answers_id` INT(11) NOT NULL,
  PRIMARY KEY (`review_id`, `answers_id`),
  INDEX `FK5lsexgleorhd8oisiiq3ew9ld` (`answers_id` ASC) VISIBLE,
  CONSTRAINT `FK5lsexgleorhd8oisiiq3ew9ld`
    FOREIGN KEY (`answers_id`)
    REFERENCES `tzeentch-shop`.`review` (`id`),
  CONSTRAINT `FKeegb8qjuaku3mxx35qy6p0k6f`
    FOREIGN KEY (`review_id`)
    REFERENCES `tzeentch-shop`.`review` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tzeentch-shop`.`room_messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tzeentch-shop`.`room_messages` (
  `room_id` INT(11) NOT NULL,
  `messages_id` INT(11) NOT NULL,
  PRIMARY KEY (`room_id`, `messages_id`),
  UNIQUE INDEX `UK_1m0nkocht3lmljiqlmaf6vluv` (`messages_id` ASC) VISIBLE,
  CONSTRAINT `FK3ampv1lcdbap8nln00joji1xo`
    FOREIGN KEY (`messages_id`)
    REFERENCES `tzeentch-shop`.`message` (`id`),
  CONSTRAINT `FKh61esxflkh1ocufq5yhxqwjpa`
    FOREIGN KEY (`room_id`)
    REFERENCES `tzeentch-shop`.`room` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tzeentch-shop`.`spring_session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tzeentch-shop`.`spring_session` (
  `PRIMARY_ID` CHAR(36) NOT NULL,
  `SESSION_ID` CHAR(36) NOT NULL,
  `CREATION_TIME` BIGINT(20) NOT NULL,
  `LAST_ACCESS_TIME` BIGINT(20) NOT NULL,
  `MAX_INACTIVE_INTERVAL` INT(11) NOT NULL,
  `EXPIRY_TIME` BIGINT(20) NOT NULL,
  `PRINCIPAL_NAME` VARCHAR(225) NULL DEFAULT NULL,
  PRIMARY KEY (`PRIMARY_ID`),
  UNIQUE INDEX `SPRING_SESSION_IX1` (`SESSION_ID` ASC) VISIBLE,
  INDEX `SPRING_SESSION_IX2` (`EXPIRY_TIME` ASC) VISIBLE,
  INDEX `SPRING_SESSION_IX3` (`PRINCIPAL_NAME` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `tzeentch-shop`.`spring_session_attributes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tzeentch-shop`.`spring_session_attributes` (
  `SESSION_PRIMARY_ID` CHAR(36) NOT NULL,
  `ATTRIBUTE_NAME` VARCHAR(200) NOT NULL,
  `ATTRIBUTE_BYTES` BLOB NOT NULL,
  PRIMARY KEY (`SESSION_PRIMARY_ID`, `ATTRIBUTE_NAME`),
  CONSTRAINT `SPRING_SESSION_ATTRIBUTES_FK`
    FOREIGN KEY (`SESSION_PRIMARY_ID`)
    REFERENCES `tzeentch-shop`.`spring_session` (`PRIMARY_ID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `tzeentch-shop`.`user_credit_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tzeentch-shop`.`user_credit_details` (
  `credit_card_number` VARCHAR(255) NULL DEFAULT NULL,
  `sum_of_money` DECIMAL(19,2) NULL DEFAULT NULL,
  `id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FKhe93j9yh2yhdqg8oqqixip1h1`
    FOREIGN KEY (`id`)
    REFERENCES `tzeentch-shop`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tzeentch-shop`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tzeentch-shop`.`user_role` (
  `user_id` INT(11) NOT NULL,
  `roles` VARCHAR(255) NULL DEFAULT NULL,
  INDEX `FK859n2jvi8ivhui0rl0esws6o` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK859n2jvi8ivhui0rl0esws6o`
    FOREIGN KEY (`user_id`)
    REFERENCES `tzeentch-shop`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
